/**
 * @author Chris Crocetti
 */

let companyName = "Your Company";
let companyNameFull = "Your Company Full Name LLC"

let grammars = {
    bs_mission: {
        question: ["How do you #verb# #adjective#?",
                   "What is the #adjective# of #place#?",
                   "What is the #adjective# of #noun#?",
                   "How do you #verb# #place#?",
                   'What does "#phrase#" mean?',
                   'What does the term "#subject#" really mean?',
                   'Is your #businessType# ready for #place#?',
                   'Is #verbing# the future of #place#?',
                   'What is the future of #technology#?',
                   'Can we leverage #technology# for our #businessType#?',
                   'Can we afford #technology#?',
                   'Can we afford to ignore #technology#?',
                   'Can we bring the power of #technology# to #technology#?'],
        answer: ['#question# #answer#', "We can!", "#belief.capitalize#.", "It's true!",
                 "#verbing.capitalize# #subject# #noun#.", "And how!", "#noun.capitalize#!",
                 "Great question!", '#companyName# is the answer!', 'Ask #companyName#!',
                 'Well let us ask you this: #question#', 'Think #technology#!',
                 'Can you afford not to?', 'We\'ve got the answer!', 'Great minds think alike!'],
        adjective: ["future", "abstraction", "meaning", "optimization", "best"],
        noun: ['content', 'standards', 'information', 'resources', 'methods',
                'creations', 'access', 'synergies', 'expectations', 'paradigms',
                'opportunities', 'products', 'practices', 'best practices',
                'strategies', 'solutions', 'brands', 'platforms',],
        subject: [
                'enterprise-wide', 'network', 'multimedia', 'professional', 'corporate',
                'competitive', 'efficient', 'high-quality', 'cost-effective', 'the best',
                'existing', 'dramatic', 'out-of-the-box', 'strategic', 'optimized',
                'deliverable', 'secure', 'forward thinking', 'leading-edge', 'bleeding-edge',
                'cutting-edge', 'industry standard', 'gold standard', 'award-winning',
                "24/7", "24/7/365", "60/24/7/365", "60/60/24/7/365"],
        cyberplace: ["the cyber#noun#", "cyber-#noun#", "e-#noun#", "the meta#noun#",],
        place: ["enterprise", "the future", "e-commerce", "the internet", "e-space",
                "the metaverse", "social media", "#cyberplace#"],
        phrase: ["#verb# the #adjective# of #place#", "#verb# #subject# #noun#",],
        phrasePast: ["#verb.ed# the #adjective# of #place#", "#verb.ed# #adjective# #noun#",],
        verb: [ 'leverage', 'fashion', 'revolutionize', 'initiate',
                'mediate', 'outsource', 'synergize',
                'maintain', 'enhance', 'promote', 'envision', 'reimagine',
                'provide', 'execute', 'deliver', 'optimize', 'ideate',
                'mitigate', 'produce'],
        verbing: ['leveraging', 'fashioning', 'revolutionizing', 'initiating',
                  'mediating', 'outsourcing', 'promoting', 'synergizing', 'winning',
                  'maintaining', 'enhancing', 'envisioning', 'reimagining',
                  'providing', 'executing', 'delivering', 'optimizing', 'ideating',
                  'mitigating', 'producing'],
        choices: ['choices', 'paths ahead', 'options', 'ways forward',],
        leadAdj: ['leader', 'gold standard', 'industry standard', 'last word', 'industry leader'],
        belief: ["we know how to #phrase#", "we can #phrase#"],
        feeling: ["believe", "strongly believe", "feel that", "understand", "envison"],
        guideNoun: "guide chaperone concierge sherpa navigator guru usher pathfinder mentor".split(' '),
        businessType: "business enterprise e-business platform".split(' '),
        technology: ["Java", "J2EE", "Ruby on Rails", "Web3", "Web 2.0", "Python", "Dynamic HTML",
                     "Fortran", "COBOL", "the Web", "the Metaverse", "IoT", "AI", "Machine Learning",
                     "Django", "C++", "PHP", "HTTP", "the Dark Web", "IIS", "Nginx", "React", "Node.js",
                     "MongoDB", "Crypto", "NFTs",
                     "#technology# 2.0", "native #technology#", "enterprise #technology#",
                     "#subject.capitalize# #technology#",],
        bodyText: ['We #feeling# #verbing# #noun# is the #adjective# of #noun#!',
                   'We #verb# the #subject# so you don\'t have to!',
                   '#question# #answer#',
                   'We know you have many #choices# when it comes to #verbing# #noun#.  #companyName# is the #leadAdj# for your #businessType#.',
                   'In #place#, you have many #choices#.  Your #guideNoun#? #companyName#.',
                   'Think #place#.', 'Think #subject#.', 'Think the #leadAdj# of #subject# #noun#.', 'Think #noun#.', 'Think #technology#.',
                   'We bring the power of #technology# to bear for your #businessType#.',
                   'We join #technology# and #technology# to truly #phrase#.',
                   'Only #companyNameFull# brings #technology# to #place#.',
                   'Only #companyNameFull# is capable of #verbing# #technology# while #verbing# #technology#.'
                   ],
        intro: ['At #companyNameFull#, we #feeling# #belief#.',
                '#companyNameFull# has #phrasePast#.',
                '#companyName# is the #leadAdj# in #subject# #noun#.',
                '#companyNameFull#.  The #leadAdj# in #subject# #noun#.',
                ],
        missionBody : ['<p>#bodyText# #bodyText# #bodyText# #bodyText# #bodyText#</p>' +
                       '<p>#bodyText# #bodyText# #bodyText#</p>' +
                       '<p>#bodyText# #bodyText# #bodyText# #bodyText# #bodyText#</p>' +
                       '<p>#companyName#.  We know what\'s best for your business.</p>'],
        companyName: companyName,
        companyNameFull: companyNameFull,
        origin : "<div>#intro# #missionBody#</div>"
    },
    bs_slogan: {
        verb: ['Leveraging', 'Fashioning', 'Revolutionizing', 'Initiating',
        'Mediating', 'Outsourcing', 'Promoting', 'Synergizing', 'Winning',
        'Maintaining', 'Enhancing', 'Promoting', 'Envisioning', 'Reimagining',
        'Providing', 'Executing', 'Delivering', 'Optimizing', 'Ideating',
        'Mitigating', 'Producing'],
        subject: [
        'enterprise-wide', 'network', 'multimedia', 'professional', 'corporate',
        'competitive', 'efficient', 'high-quality', 'cost-effective', 'the best',
        'existing', 'dramatic', 'out-of-the-box', 'strategic', 'optimized',
        'deliverable', 'secure', 'forward thinking', 'gold standard', 'cutting-edge',
        'leading-edge', 'bleeding-edge', 'award-winning'],
        object: ['content', 'standards', 'information', 'resources', 'methods',
        'creations', 'access', 'synergies', 'expectations', 'paradigms',
        'opportunities', 'products', 'practices', 'best practices',
        'strategies', 'solutions', 'brands',],
        origin: "#verb# #subject# #object#.",
    },
    bs_bio: {
        business: ["Freedonia Web Design", "Gnomox Industrial Concern", "Kabalypse Networking Concern LLC", "Artmill Inc.",
                    "IBM", "Microsoft", "Mozilla", "Snapchat", "Facebook", "Google", "Red Hat", "Alphabet", "Meta", "Oracle", 
                    "Initech", "an unspecified dark web startup", "Blabr", "Bznezz", "StarTup", "BullShip", "Los Pollos Hermanos"
                  ],
        school: ["Laurentian University", "Harvard", "Stanford", "Yale Business School", "MIT", "Univeristy of Toronto", "University of Waterloo", "Hollywood Upstairs Medical College"],
        discipline: ["technology", "IT", "design", "web design", "software development", "software engineering", "digital management",
                     "excellence", "management studies", "bio-ethics", "synergy management"],
        technology: ["Java", "J2EE", "Ruby on Rails", "Web3", "Web 2.0", "Python", "Dynamic HTML",
                     "Fortran", "COBOL", "the Web", "the Metaverse", "IoT", "AI", "Machine Learning",
                     "Django", "C++", "PHP", "HTTP", "the Dark Web", "IIS", "Nginx", "React", "Node.js",
                     "MongoDB", "Crypto", "NFTs",
                     "#technology# 2.0", "native #technology#", "enterprise #technology#",
                     "#subject.capitalize# #technology#"],
        hobbies: ["cooking", "baking", "hiking", "mountain climbing", "amateur boxing", "race-car driving",
                  "playing #music#", "skydiving", "bungee-jumping", "hang gliding", "traveling", "working on cars",
                  "playing sportsball", "#hobbies# and #hobbies#",
                 ],
        music: ["folk", "bluegrass", "country", "heavy metal", "jazz", "rockabilly", "rock-n-roll", "surf rock", "death metal", "polka",
                "punk rock", "EDM", "classical", "electro house", "#music#-#music#", "fusion #music#", "neo-#music#", "classic #music#"],
        number: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15", "75 combined"],
        numberText: ["one","two","three","four","five","six","seven","eight","nine","ten","fifteen"],
        journeyContinued: ["joining the #discipline# team at #business#",
                           "working for such companies as #business# and #business#",
                           "traveling the world gaining valuable experience in the field of #discipline#",
                           "revolutionizing the world of #technology# at #business#"
                          ],
        journeyStart: ["started his career at #business#",
                       "studied #discipline# at #school#",
                       "got his start at #business# #verbing# #noun#"
                      ],
        actionVerb: ["delivers", "excels", "provides"],
        verbing: ['leveraging', 'fashioning', 'revolutionizing', 'initiating',
                  'mediating', 'outsourcing', 'promoting', 'synergizing', 'winning',
                  'maintaining', 'enhancing', 'envisioning', 'reimagining',
                  'providing', 'executing', 'delivering', 'optimizing', 'ideating',
                  'mitigating', 'producing'],
        noun: ['content', 'standards', 'information', 'resources', 'methods',
              'creations', 'access', 'synergies', 'expectations', 'paradigms',
              'opportunities', 'products', 'practices', 'best practices',
              'strategies', 'solutions', 'brands', 'platforms',],
        subject: [
              'enterprise-wide', 'network', 'multimedia', 'professional', 'corporate',
              'competitive', 'efficient', 'high-quality', 'cost-effective', 'the best',
              'existing', 'dramatic', 'out-of-the-box', 'strategic', 'optimized',
              'deliverable', 'secure', 'forward thinking', 'leading-edge', 'bleeding-edge',
              'cutting-edge', 'industry standard', 'gold standard', 'award-winning',
              "24/7", "24/7/365", "60/24/7/365", "60/60/24/7/365"],
        moreThan: ["", "", "", "more than ", "over "],
        experience: ["#numberText#-years' experience at #business#",
                     "#numberText#-years' experience at #business# to #companyName#",
                     "#number# years' experience in #technology# and #technology#",
                     "#number# years' experience in #technology# and #technology# to #companyName#",
                     "#number# years' experience in #technology# at #business#"],
        bringAction: ["bring", "deliver", "offer"],
        enjoys: ["enjoys", "spends his time", "travels the world", "is passionate about"],
        companyName: companyName,
        firstSentence: ["#firstName# #journeyStart# before #journeyContinued#.",
                        "After he #journeyStart#, #firstName# #bringAction.s# #moreThan# #experience#.",
                        "#firstName# #bringAction.s# #moreThan# #experience#.",
                        "#firstName# comes to #companyName# from #business#, where he excelled at #subject# #noun#.",
                        "When #firstName# joined #companyName#, he filled us with tales of #journeyContinued#."
                    ],
        nextSentence: ["While revolutionizing the field of #discipline#, #firstName# also #actionVerb# at #verbing# #noun#.",
                       "When #firstName# isn't #verbing# #subject# #noun#, he's #verbing# #subject# #noun#.",
                       "#firstName# is proud to #bringAction# #subject# #noun# to #companyName#.",
                      ],
        personal: ["#firstName# #enjoys# #hobbies# and #hobbies#.",
                   "When not innovating in the field of #discipline#, #firstName# can be found #hobbies# in his spare time.",
                   "Loves #hobbies#.",
                   "Enjoys #hobbies# and #hobbies#."
               ],
        body: ["<h3>#firstName# #lastName#</h3><div>#firstSentence# #nextSentence# #personal#</div>"],
        origin: ["#body#"]
    },
    bs_jobtitle: {
        seniority: "Junior Senior Lead Freelance Chief Vice Interim #seniority#-#seniority# Principal Internal Global International District Regional National Local Interstellar".split(" "),
        title: "President Vice-President Manager Head Engineer Guru Scholar Master Director Synergist Supervisor Liason Officer Coordinator Administrator Architect Designer Orchestrator Technician Developer Producer Consultant Assistant Representative Strategist Rockstar Ninja Evangelist Prophet".split(" "),
            predivision: ["Web ", "Cyber ", "Enterprise ", "Product ", "Metaverse ", "E-", "Future ", "Theoretical ", "Applied ", "Award-Winning "],
        userDisciplines: "Studies Impact Stories Interaction Narratives Education Colloquy".split(" "),
        division: [
            "#companyName# #division#",
            "Engineering", "Brand Synergy", "Software", "Hardware", "Firmware", "Applications",
            "Creative", "Interactivity", "User #userDisciplines#", "#predivision##division#",
            "Synergy", "Brands", "Public Relations",
        ],
        companyName: companyName,
        origin: ["#seniority# #title# of #division#", "#seniority# #division# #title#"],
    },
}
